name: Back CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths: 'back/**'

jobs:
  build:
    name: CI - Build Spring Boot Back
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
        
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests with coverage
        run: mvn clean verify

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: back-coverage
          path: back/target/site/jacoco  
